name: Publish

on: 
  push:
    branches: 
      - main
env:
  AZURE-WEBAPP-NAME: OfficeBoard
  AZURE-WEBAPP-PACKAGE-PATH: "./pulish"
  
jobs:
  build_and_test:
    runs-on: windows-latest

    steps:
        # Checkout branche
        - name: Checkout
          uses: actions/checkout@v3.0.2

        # Use lastest .NET Core SDK for build
        - name: Setup .NET Core SDK
          uses: actions/setup-dotnet@v2.1.0
          with:
            dotnet-version: 6.0.x
        
        # Restore dependencies in the solution
        - name: Restore dependencies
          run: dotnet restore

        # Setup NuGet to get packages
        - name: Setup NuGet
          uses: NuGet/setup-nuget@v1.0.6
          with:
            nuget-version: latest

        # Restore NuGet packages if present
        - name: Restore NuGet packages
          run: nuget restore #./TestGit/Project.sln
        
        # Build project
        - name: Build project
          run: dotnet build --configuration Release --no-restore #./TestGit/Project.sln
        
        # Publish Applicaton
        - name: publish
          run: dotnet publish  --configuration Release --no-build #./TestGit/Project.sln --output '${{env.AZURE-WEBAPP-PACKAGE-PATH}}'
        
        # Deploy Applicaton
        - name: Deployment
          uses: azure/webapps-deploy@v2
          with:
            app-name: ${{env.AZURE-WEBAPP-NAME}}
            publish-profile: ${{secrets.AZURE_PUBLISH_PROFILE}}
            package: '${{env.AZURE-WEBAPP-PACKAGE-PATH}}'
